Update GCSAdapter methods to reflect latest client API
parse-community/parse-server-gcs-adapter pull request #31
Opened 2021-01-24 06:27 UTC by pmmlo

2021-01-24 06:27 UTC, pmmlo commented
@TomWFox Here's the PR in a commit, if you could take a look.  Thanks

2021-01-26 18:02 UTC, TomWFox commented
Thanks for the PR! Unfortunately I'm not best placed to review this.

2021-01-26 22:31 UTC, motte commented
> Thanks for the PR! Unfortunately I'm not best placed to review this.

No worries!  Will try someone else.

2021-01-26 22:37 UTC, pmmlo commented
> Thanks for the PR! Unfortunately I'm not best placed to review this.

No worries!  Thanks for sending over to core-mainters.  Cheers!

2021-01-28 23:57 UTC, davimacedo requested changes
Please find  some comments below. Would you mind to share a link with the changes of the last API? Also, could you please run tests and fix the errors?

2021-01-28 23:57 UTC, davimacedo commented on index.js
> +  uploadFile().catch(console.error);
I believe we should await. And also not only output the error to the console but let it be thrown.

2021-01-28 23:57 UTC, davimacedo commented on index.js
> +    deleteFile().catch(console.error);
same thing here

2021-01-28 23:57 UTC, davimacedo commented on index.js
> +    downloadFile().catch(console.error);
here we also need to return the data

2021-02-02 23:13 UTC, pmmlo commented
> Please find some comments below. Would you mind to share a link with the changes of the last API? Also, could you please run tests and fix the errors?

@davimacedo Thanks for taking a look.

I agree about the await and returning on file upload.  I just wanted to keep it as close to original as possible for the first PR.  I think the original file upload also did not return anything.

I actually am not setup to use this adapter and fully test it.  I'll setup a demo account and reopen when I have more time.

Cheers!

2021-02-02 23:13 UTC, closed without merging